/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void forward_click(GButton source, GEvent event) { //_CODE_:forwardBtn:875208:
  connexion.write("w");
  inputText.appendText("Mode 1: Forward");
} //_CODE_:forwardBtn:875208:

public void left_click(GButton source, GEvent event) { //_CODE_:leftBtn:763555:
  connexion.write("a");
  inputText.appendText("Mode 1: Left");
} //_CODE_:leftBtn:763555:

public void backward_click(GButton source, GEvent event) { //_CODE_:backwardBtn:692782:
  connexion.write("s");
  inputText.appendText("Mode 1: Backward");
} //_CODE_:backwardBtn:692782:

public void right_click(GButton source, GEvent event) { //_CODE_:rightBtn:813966:
  connexion.write("d");
  inputText.appendText("Mode 1: Right");
} //_CODE_:rightBtn:813966:

public void mode1Stop_click(GButton source, GEvent event) { //_CODE_:stopBtn:705492:
  connexion.write("x");
    inputText.appendText("Mode 1: STOP");
} //_CODE_:stopBtn:705492:

public void mode3Start_click(GButton source, GEvent event) { //_CODE_:mode3StartBtn:515840:
   connexion.write("3");
     inputText.appendText("Mode 3: Start");
} //_CODE_:mode3StartBtn:515840:

public void mode3Stop_click(GButton source, GEvent event) { //_CODE_:mode3StopBtn:393329:
  connexion.write("x");
    inputText.appendText("Mode 3: STOP");
} //_CODE_:mode3StopBtn:393329:

public void mode2Left_click(GButton source, GEvent event) { //_CODE_:mode2LeftBtn:511403:
  connexion.write("l");
    inputText.appendText("Mode 2: Left");
} //_CODE_:mode2LeftBtn:511403:

public void mode2Right_click(GButton source, GEvent event) { //_CODE_:mode2RightBtn:773324:
  connexion.write("r");
    inputText.appendText("Mode 2: Right");
} //_CODE_:mode2RightBtn:773324:

public void mode2Start_click(GButton source, GEvent event) { //_CODE_:mode2Start:628733:
  connexion.write("2");
    inputText.appendText("Mode 2: Start");
} //_CODE_:mode2Start:628733:

public void mode2Stop_click(GButton source, GEvent event) { //_CODE_:mode2StopBtn:849604:
  connexion.write("x");
    inputText.appendText("Mode 2: STOP");
} //_CODE_:mode2StopBtn:849604:

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:inputText:253549:
  println("inputText - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:inputText:253549:

public void outputText_change(GTextArea source, GEvent event) { //_CODE_:outputText:270982:
  
} //_CODE_:outputText:270982:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  forwardBtn = new GButton(this, 110, 80, 80, 30);
  forwardBtn.setText("Forward");
  forwardBtn.addEventHandler(this, "forward_click");
  leftBtn = new GButton(this, 30, 120, 80, 30);
  leftBtn.setText("Left");
  leftBtn.addEventHandler(this, "left_click");
  label1 = new GLabel(this, 100, 10, 100, 50);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Mode 1");
  label1.setOpaque(false);
  backwardBtn = new GButton(this, 110, 160, 80, 30);
  backwardBtn.setText("Backward");
  backwardBtn.addEventHandler(this, "backward_click");
  rightBtn = new GButton(this, 190, 120, 80, 30);
  rightBtn.setText("Right");
  rightBtn.addEventHandler(this, "right_click");
  stopBtn = new GButton(this, 110, 220, 80, 30);
  stopBtn.setText("STOP");
  stopBtn.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  stopBtn.addEventHandler(this, "mode1Stop_click");
  label2 = new GLabel(this, 450, 10, 100, 50);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Mode 2");
  label2.setOpaque(false);
  label3 = new GLabel(this, 800, 10, 100, 50);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Mode 3");
  label3.setOpaque(false);
  mode3StartBtn = new GButton(this, 800, 80, 100, 100);
  mode3StartBtn.setText("Start Autonomous");
  mode3StartBtn.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  mode3StartBtn.addEventHandler(this, "mode3Start_click");
  mode3StopBtn = new GButton(this, 800, 220, 100, 50);
  mode3StopBtn.setText("STOP Autonomous");
  mode3StopBtn.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  mode3StopBtn.addEventHandler(this, "mode3Stop_click");
  mode2LeftBtn = new GButton(this, 370, 140, 80, 30);
  mode2LeftBtn.setText("Left");
  mode2LeftBtn.addEventHandler(this, "mode2Left_click");
  mode2RightBtn = new GButton(this, 550, 140, 80, 30);
  mode2RightBtn.setText("Right");
  mode2RightBtn.addEventHandler(this, "mode2Right_click");
  mode2Start = new GButton(this, 450, 80, 100, 50);
  mode2Start.setText("Start/Continue");
  mode2Start.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  mode2Start.addEventHandler(this, "mode2Start_click");
  mode2StopBtn = new GButton(this, 460, 220, 80, 30);
  mode2StopBtn.setText("STOP");
  mode2StopBtn.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  mode2StopBtn.addEventHandler(this, "mode2Stop_click");
  inputText = new GTextArea(this, 30, 300, 460, 170, G4P.SCROLLBARS_NONE);
  inputText.setOpaque(true);
  inputText.addEventHandler(this, "textarea1_change1");
  outputText = new GTextArea(this, 510, 300, 460, 170, G4P.SCROLLBARS_NONE);
  outputText.setOpaque(true);
  outputText.addEventHandler(this, "outputText_change");
  inputLabel = new GLabel(this, 30, 280, 100, 20);
  inputLabel.setText("Input Text Field");
  inputLabel.setOpaque(false);
  label4 = new GLabel(this, 510, 280, 100, 20);
  label4.setText("Output Text Field");
  label4.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton forwardBtn; 
GButton leftBtn; 
GLabel label1; 
GButton backwardBtn; 
GButton rightBtn; 
GButton stopBtn; 
GLabel label2; 
GLabel label3; 
GButton mode3StartBtn; 
GButton mode3StopBtn; 
GButton mode2LeftBtn; 
GButton mode2RightBtn; 
GButton mode2Start; 
GButton mode2StopBtn; 
GTextArea inputText; 
GTextArea outputText; 
GLabel inputLabel; 
GLabel label4; 
